# Generated by Django 5.0.9 on 2025-05-26 19:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the HOA', max_length=200)),
                ('address', models.TextField(help_text='Physical address of the HOA')),
                ('contact_email', models.EmailField(help_text='Primary contact email for the HOA', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('management_company', models.CharField(blank=True, help_text='Name of the management company (if any)', max_length=200, null=True)),
                ('website', models.URLField(blank=True, help_text='HOA website URL', null=True)),
                ('established_date', models.DateField(blank=True, help_text='Date when HOA was established', null=True)),
                ('total_units', models.PositiveIntegerField(default=0, help_text='Total number of units managed by this HOA')),
                ('monthly_fee_range', models.CharField(blank=True, help_text="Monthly fee range (e.g., '$200-$400')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HOA',
                'verbose_name_plural': 'HOAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Property address')),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family Home'), ('townhouse', 'Townhouse'), ('condo', 'Condominium'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('other', 'Other')], default='single_family', help_text='Type of property', max_length=20)),
                ('unit_count', models.PositiveIntegerField(default=1, help_text='Number of units in this property (1 for single family homes)')),
                ('square_footage', models.PositiveIntegerField(blank=True, help_text='Total square footage', null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, help_text='Year the property was built', null=True)),
                ('monthly_hoa_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly HOA fee for this property', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this property is actively managed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoa', models.ForeignKey(help_text='HOA that manages this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='hoa_management.hoa')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['address'],
            },
        ),
    ]
