# Generated by Django 5.0.9 on 2025-05-28 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoa_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique message ID from email provider', max_length=255, unique=True)),
                ('from_email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('raw_content', models.TextField(help_text='Full raw email content')),
                ('html_content', models.TextField(blank=True, help_text='HTML version of email content', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Plain text version of email content', null=True)),
                ('manages_properties', models.BooleanField(blank=True, help_text='Does HOA manage the listed properties?', null=True)),
                ('properties_confirmation', models.TextField(blank=True, help_text='Details about property management confirmation', null=True)),
                ('regular_dues_amount', models.CharField(blank=True, help_text='Amount of regular HOA dues', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Preferred payment method', max_length=200, null=True)),
                ('payment_address', models.TextField(blank=True, help_text='Mailing address for payments', null=True)),
                ('master_hoa_name', models.CharField(blank=True, help_text='Name of master HOA if any', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number for HOA business', max_length=20, null=True)),
                ('management_company', models.CharField(blank=True, help_text='Management company name', max_length=200, null=True)),
                ('response_completeness_score', models.IntegerField(default=0, help_text='Completeness score from 0-100 based on answered questions')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('processed', 'Processed')], default='new', help_text='Processing status of the response', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this response was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoa', models.ForeignKey(help_text='HOA that sent this response', on_delete=django.db.models.deletion.CASCADE, related_name='email_responses', to='hoa_management.hoa')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this response', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Response',
                'verbose_name_plural': 'Email Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
