# Generated by Django 5.0.9 on 2025-06-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoa_management', '0003_emailresponse_ai_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoa',
            name='demo_email_used',
            field=models.EmailField(blank=True, help_text="Demo email address used for this HOA's onboarding", max_length=254, null=True),
        ),
    ]
